/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "gw.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gw_UplinkTXInfo, gw_UplinkTXInfo, AUTO)


PB_BIND(gw_LoRaModulationInfo, gw_LoRaModulationInfo, AUTO)


PB_BIND(gw_FSKModulationInfo, gw_FSKModulationInfo, AUTO)


PB_BIND(gw_EncryptedFineTimestamp, gw_EncryptedFineTimestamp, AUTO)


PB_BIND(gw_PlainFineTimestamp, gw_PlainFineTimestamp, AUTO)


PB_BIND(gw_GatewayStats, gw_GatewayStats, AUTO)


PB_BIND(gw_GatewayStats_MetaDataEntry, gw_GatewayStats_MetaDataEntry, AUTO)


PB_BIND(gw_UplinkRXInfo, gw_UplinkRXInfo, AUTO)


PB_BIND(gw_DownlinkTXInfo, gw_DownlinkTXInfo, AUTO)


PB_BIND(gw_ImmediatelyTimingInfo, gw_ImmediatelyTimingInfo, AUTO)


PB_BIND(gw_DelayTimingInfo, gw_DelayTimingInfo, AUTO)


PB_BIND(gw_GPSEpochTimingInfo, gw_GPSEpochTimingInfo, AUTO)


PB_BIND(gw_UplinkFrame, gw_UplinkFrame, 2)


PB_BIND(gw_UplinkFrameSet, gw_UplinkFrameSet, AUTO)


PB_BIND(gw_DownlinkFrame, gw_DownlinkFrame, AUTO)


PB_BIND(gw_DownlinkTXAck, gw_DownlinkTXAck, AUTO)


PB_BIND(gw_GatewayConfiguration, gw_GatewayConfiguration, AUTO)


PB_BIND(gw_ChannelConfiguration, gw_ChannelConfiguration, AUTO)


PB_BIND(gw_LoRaModulationConfig, gw_LoRaModulationConfig, AUTO)


PB_BIND(gw_FSKModulationConfig, gw_FSKModulationConfig, AUTO)


//PB_BIND(gw_GatewayCommandExecRequest, gw_GatewayCommandExecRequest, AUTO)


PB_BIND(gw_GatewayCommandExecRequest_EnvironmentEntry, gw_GatewayCommandExecRequest_EnvironmentEntry, AUTO)


//PB_BIND(gw_GatewayCommandExecResponse, gw_GatewayCommandExecResponse, AUTO)


PB_BIND(gw_RawPacketForwarderEvent, gw_RawPacketForwarderEvent, AUTO)


PB_BIND(gw_RawPacketForwarderCommand, gw_RawPacketForwarderCommand, AUTO)






#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

